models/Contact.php
<?php

namespace app\models;

use Yii;
use yii\db\ActiveRecord;
use yii\behaviors\TimestampBehavior;

/**
 * Contact is the model for contacts.
 * @property string $first_name First name user
 * @property string $last_name Last name user
 * @property string $patronymic Patronymic user 
 */
class Contact extends ActiveRecord
{
    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            // first name rules
            ['first_name', 'required'],
            ['first_name', 'string', 'max' => 25],

            // last name rules
            ['last_name', 'string', 'max' => 25],

            // patronymic rules
            ['patronymic', 'string', 'max' => 25],
        ];
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPhones()
    {
        return $this->hasMany(UserPhone::className(), ['contact_id' => 'id']);
    }

     /**
     * @param bool $insert
     * @param array $changedAttributes
     */
    public function afterSave($insert, $changedAttributes)
    {
        if ($insert) {            
        }
        parent::afterSave($insert, $changedAttributes);
    }

}

models/ContactForm.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;

/**
 * ContactForm is the model behind the contact form.
 */
class ContactForm extends Model
{
    public $name;
    public $email;
    public $subject;
    public $body;
    public $verifyCode;


    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            // name, email, subject and body are required
            [['name', 'email', 'subject', 'body'], 'required'],
            // email has to be a valid email address
            ['email', 'email'],
            // verifyCode needs to be entered correctly
            ['verifyCode', 'captcha'],
        ];
    }

    /**
     * @return array customized attribute labels
     */
    public function attributeLabels()
    {
        return [
            'verifyCode' => 'Verification Code',
        ];
    }

    /**
     * Sends an email to the specified email address using the information collected by this model.
     * @param string $email the target email address
     * @return bool whether the model passes validation
     */
    public function contact($email)
    {
        if ($this->validate()) {
            Yii::$app->mailer->compose()
                ->setTo($email)
                ->setFrom([$this->email => $this->name])
                ->setSubject($this->subject)
                ->setTextBody($this->body)
                ->send();

            return true;
        }
        return false;
    }
}

controllers/ContactController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\Contact;
use app\models\UserPhone;
use yii\base\UnknownClassException;

class ContactController extends Controller
{
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionCreate()
    {
        $model = \Yii::createObject(['class' => Contact::className()]);
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->save();
            $this->redirect(['/contact/view', 'id' => $model->id]);
        }
        return $this->render('create');
    }

    public function actionView($id)
    {
        $model = Contact::findOne($id);

        if (!$model) {
            throw new UnknownClassException('Contact with '.$id.' not found.');
        }

        return $this->render('view', ['id' => $id]); 
    }

    public function actionUpdate($id)
    {
        $model = Contact::findOne($id);

        if (!$model) {
            throw new UnknownClassException('Contact with '.$id.' not found.');
        } else {
            if ($model->load(Yii::$app->request->post()) && $model->validate()) {
                if ($model->save()) {
                    Yii::$app->session->setFlash('success', 'Contact successuly updated');
                } else {
                    Yii::$app->session->setFlash('error', 'Contact failure update');
            }
        }        
        }
        return $this->render('update', ['id' => $id]); 
    }

    public function actionDelete($id)
    {
        $model = Contact::findOne($id);

        if (!$model) {
            throw new UnknownClassException('Contact with '.$id.' not found.');
        } else {
            if ($model->delete()) {               
                Yii::$app->session->setFlash('success', 'Contact successuly deleted');
            } else {
                Yii::$app->session->setFlash('error', 'Contact failure delete');
            }
        }

        $this->redirect(['/contact/index']);
    }

   
}

controllers/UserPhoneController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\Contact;
use app\models\UserPhone;
use yii\base\UnknownClassException;

class UserPhoneController extends Controller
{
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }    

    public function actionCreate($contact_id)
    {
        $contact = Contact::findOne($contact_id);
        if (!$contact) {
            throw new UnknownClassException('Contact with '.$contact_id.' not found.');
        }

        if (count($contact->phones) >= 10) {
            Yii::$app->session->setFlash('error', 'Contact can have max 10 phones!');
            return $this->render('create', ['contact_id' => $contact_id]);
        }

        $model = \Yii::createObject(['class' => UserPhone::className()]);
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->save();

            Yii::$app->session->setFlash('success', 'Phone number successuly added.');

            $this->redirect(['/contact/view', 'id' => $contact_id]);
        }
        return $this->render('create', ['contact_id' => $contact_id]);
    }    

    public function actionUpdate($id, $contact_id)
    {
        $model = UserPhone::findOne($id);

        if (!$model) {
            throw new UnknownClassException('Contact with '.$id.' not found.');
        } else {
            if ($model->load(Yii::$app->request->post()) && $model->validate()) {
                if ($model->save()) {
                    Yii::$app->session->setFlash('success', 'Phone successuly updated');
                } else {
                Yii::$app->session->setFlash('error', 'Phone failure update');
            }
            } 
        }

        return $this->render('update', ['id' => $id, 'contact_id' => $contact_id]); 
    }

    public function actionDelete($id)
    {
        $model = UserPhone::findOne($id);

        if (!$model) {
            throw new UnknownClassException('Phone with '.$id.' not found.');
        } else {
            if ($model->delete()) {               
                Yii::$app->session->setFlash('success', 'Phone successuly deleted');
            } else {
                Yii::$app->session->setFlash('error', 'Phone failure delete');
            }
        }

        $this->redirect(['/contact/index']);
    }

   
}

views/contact/create.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use app\models\Contact;

$this->title = 'Create Contact';
$this->params['breadcrumbs'][] = $this->title;

$model = \Yii::createObject(['class' => Contact::className()]);
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
    ]); ?>

        <?= $form->field($model, 'first_name')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'last_name')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'patronymic')->textInput(['autofocus' => true]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Create', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>
   
</div>

views/contact/index.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use app\models\Contact;
use yii\grid\GridView;
use yii\data\ActiveDataProvider;

$this->title = 'Contacts';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>
<?php 
$dataProvider = new ActiveDataProvider([
    'query' => Contact::find(),
    'pagination' => [
        'pageSize' => 20,
    ],
]);

echo GridView::widget([
            'dataProvider'      => $dataProvider,
            'filterRowOptions'  => ['class' => 'hidden-xs hidden-sm'],
            'columns'       => [
            // first name
                [
                    'attribute'         => 'first_name',
                    'format'            => 'raw',
                    'value'             => function(Contact $contact) {
                    	return Html::tag('span', $contact->first_name, ['class' => 'name']);
                    },
                ],
            // last name
                [
                    'attribute'         => 'last_name',
                    'format'            => 'raw',
                    'value'             => function(Contact $contact) {
                    	$last_name = $contact->last_name ? $contact->last_name : 'not set';
                    	return Html::tag('span', $last_name, ['class' => 'name']);
                    },
                ],
            // patronymic
                [
                    'attribute'         => 'patronymic',
                    'format'            => 'raw',
                    'value'             => function(Contact $contact) {
                    	$patronymic = $contact->patronymic ? $contact->patronymic : 'not set';
                    	return Html::tag('span', $patronymic, ['class' => 'name']);
                    },
                ],
                // phones
                [
                    'attribute'         => 'phones',
                    'format'            => 'raw',
                    'value'             => function(Contact $contact) {
                        $phones = '';
                        if (!empty($contact->phones)) {
                            foreach ($contact->phones as $phone) {
                                 $phones .= Html::tag('span', $phone->phone_number, ['class' => 'name']).'<br>';
                            }                           
                        } else {
                            $phones = 'not set';
                        }
                        return Html::tag('span', $phones, ['class' => 'name']);
                    },
                ],
            // created_at
                [
                    'attribute'         => 'created_at',
                    'format'            => 'raw',
                    'value'             => function(Contact $contact) {                    	
                    	return Html::tag('span', date("m.d.y", $contact->created_at), ['class' => 'name']);
                    },
                ],
            // updated_at
                [
                    'attribute'         => 'updated_at',
                    'format'            => 'raw',
                    'value'             => function(Contact $contact) {                    	
                    	return Html::tag('span', date("m.d.y", $contact->updated_at), ['class' => 'name']);
                    },
                ],
            // edit
                [
                    'attribute'         => '',
                    'format'            => 'raw',
                    'value'             => function(Contact $contact) {                    	
                    	return Html::a('Edit', ['contact/update', 'id' => $contact->id], ['class' => 'profile-link']);
                    },
                ],
            // view
                [
                    'attribute'         => '',
                    'format'            => 'raw',
                    'value'             => function(Contact $contact) {                    	
                    	return Html::a('View', ['contact/view', 'id' => $contact->id], ['class' => 'profile-link']);
                    },
                ],
            // delete
                [
                    'attribute'         => '',
                    'format'            => 'raw',
                    'value'             => function(Contact $contact) {                    	
                    	return Html::a('Delete', ['contact/delete', 'id' => $contact->id], ['class' => 'profile-link']);
                    },
                ],
            ]
        ]);
?>
</div>

views/contact/update.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use app\models\Contact;
use app\models\UserPhone;
use yii\data\ActiveDataProvider;
use yii\grid\GridView;


$this->title = 'Update Contact';
$this->params['breadcrumbs'][] = $this->title;

$model = Contact::findOne($id);
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
    ]); ?>

        <?= $form->field($model, 'first_name')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'last_name')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'patronymic')->textInput(['autofocus' => true]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Update', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>
    <?php 
        $dataProvider = new ActiveDataProvider([
            'query' => UserPhone::find()->where(['contact_id' => $id]),
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);

        echo GridView::widget([
                    'dataProvider'      => $dataProvider,
                    'filterRowOptions'  => ['class' => 'hidden-xs hidden-sm'],
                    'columns'       => [
                    // phone number
                        [
                            'attribute'         => 'phone_number',
                            'format'            => 'raw',
                            'value'             => function(UserPhone $userPhone) {
                                return Html::tag('span', $userPhone->phone_number, ['class' => 'name']);
                            },
                        ],          
                    // edit
                        [
                            'attribute'         => '',
                            'format'            => 'raw',
                            'value'             => function(UserPhone $userPhone) {                     
                                return Html::a('Edit', ['user-phone/update', 'id' => $userPhone->id, 'contact_id' => $userPhone->contact_id], ['class' => 'profile-link']);
                            },
                        ],
                    // delete
                        [
                            'attribute'         => '',
                            'format'            => 'raw',
                            'value'             => function(UserPhone $userPhone) {                     
                                return Html::a('Delete', ['user-phone/delete', 'id' => $userPhone->id], ['class' => 'profile-link']);
                            },
                        ],
                    ]
                ]);
    ?>

    <?= Html::a('Add phone', ['/user-phone/create', 'contact_id' => $id], ['class' => 'profile-link']) ?>
   
</div>

views/contact/view.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use app\models\Contact;
use app\models\UserPhone;
use yii\data\ActiveDataProvider;
use yii\grid\GridView;

$this->title = 'View Contact '.$id;
$this->params['breadcrumbs'][] = $this->title;

$model = Contact::findOne($id);
?>

<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>
 	<p>First name: <?=$model->first_name;?> </p>
 	<p>Last name: <?=$model->last_name;?> </p>
 	<p>Patronymic name: <?=$model->patronymic;?> </p>

 	<?= Html::a('Update', ['contact/update', 'id' => $id], ['class' => 'profile-link']) ?>

<?php 
$dataProvider = new ActiveDataProvider([
    'query' => UserPhone::find()->where(['contact_id' => $id]),
    'pagination' => [
        'pageSize' => 20,
    ],
]);

echo GridView::widget([
            'dataProvider'      => $dataProvider,
            'filterRowOptions'  => ['class' => 'hidden-xs hidden-sm'],
            'columns'       => [
            // phone number
                [
                    'attribute'         => 'phone_number',
                    'format'            => 'raw',
                    'value'             => function(UserPhone $userPhone) {
                    	return Html::tag('span', $userPhone->phone_number, ['class' => 'name']);
                    },
                ],          
            // edit
                [
                    'attribute'         => '',
                    'format'            => 'raw',
                    'value'             => function(UserPhone $userPhone) {                    	
                    	return Html::a('Edit', ['user-phone/update', 'id' => $userPhone->id, 'contact_id' => $userPhone->contact_id], ['class' => 'profile-link']);
                    },
                ],
            // delete
                [
                    'attribute'         => '',
                    'format'            => 'raw',
                    'value'             => function(UserPhone $userPhone) {                    	
                    	return Html::a('Delete', ['user-phone/delete', 'id' => $userPhone->id], ['class' => 'profile-link']);
                    },
                ],
            ]
        ]);
?>

 	<?= Html::a('Add phone', ['/user-phone/create', 'contact_id' => $id], ['class' => 'profile-link']) ?>

</div>